# IndexerExecutor config
#
path: "./test-checkpoints"
# IOTA Node Rest API URL
remote_store_url: "http://localhost:9000/api/v1"

# DynamoDbProgressStore config
#
progress_store:
  aws_access_key_id: "test"
  aws_secret_access_key: "test"
  aws_region: "us-east-1"
  # DynamoDB table name
  table_name: "checkpoint-progress"

# Wrokers Configs
#
tasks:
  # Task unique name
  - name: "local-blob-storage"
    # Number of workers will process the checkpoints in parallel
    concurrency: 1
    # Task type
    blob:
      # S3 bucket where checkpoints will be stored
      url: "s3://checkpoints"
      # AWS S3 client config options
      remote_store_options:
        - ["access_key_id", "test"]
        - ["secret_access_key", "test"]
        - ["region", "us-east-1"]
        # Only needed if using Localstack for local development purposes, it's preferred to be removed
        - ["endpoint_url", "http://localhost:4566"]
