[package]
name = "move-trace-format"
version = "0.0.1"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move Trace Format"

[dependencies]
move-binary-format.workspace = true
move-core-types.workspace = true
serde.workspace = true

serde_json = { workspace = true, features = ["arbitrary_precision"] }

[features]
default = []
