services:
  kv-remote-store:
    image: iotaledger/iota-data-ingestion
    volumes:
      - ./config.yaml:/iota/config.yaml:r
      - ./output:/iota/output
    command: >
      iota-data-ingestion
      /iota/config.yaml
