# IndexerExecutor config
#
# The local path where checkpoints are stored. For optimal performance,
# this should match the IOTA Node's ingestion path when running on the same host.
# Using the same path as the Node allows direct file access instead of HTTP requests,
# significantly improving sync speed.
path: "./test-checkpoints"
# IOTA Node Rest API URL
#
# The IOTA Node's REST API URL acts as a fallback mechanism for fetching checkpoints
# when they are not available in the local ingestion path. This provides redundancy
# and ensures data availability even when local files are not accessible.
#
# Note: This URL is optional when:
# 1. The ingestion path matches the IOTA Node's path on same host machine)
# 2. You don't need a fallback mechanism for data retrieval
# 3. Local filesystem access is sufficient for your use case
#
# Required when:
# 1. Running on a different host than the IOTA Node
# 2. Using a different path than the Node
# 3. HTTP access is preferred over local filesystem
remote-store-url: "http://localhost:9000/api/v1"

# Path to the progress store JSON file.
#
# The ingestion pipeline uses this file to persist its progress,
# ensuring state is preserved across restarts.
#
progress-store-path: "/iota/output/historical_ingestion_progress.json"

metrics-port: 8082

# Workers Configs
#
tasks:
  # Task unique name
  #
  # This task is responsible for storing entire checkpoint blobs into an S3 compatible bucket
  # Useful for Indexer's ingestion pipeline as a fallback mechanism for checkpoint synchronization
  - name: "local-historical-storage"
    # Number of workers will process the checkpoints in parallel
    concurrency: 1
    # Task type
    historical:
      # remote Object Store config for more info:
      # - https://docs.iota.org/operator/archives#set-up-archival-fallback
      #
      object-store-config:
        object-store: "S3"
        aws-endpoint: "http://localhost:4566"
        bucket: "checkpoints"
        aws-access-key-id: "test"
        aws-secret-access-key: "test"
        aws-allow-http: true
        object-store-connection-limit: 20
      # Set the time threshold (in seconds) that determines when to finalize a batch of checkpoints
      # and upload them as a single file to the object store.
      #
      # This controls how many checkpoints are grouped together in a single file:
      # - Lower values = More files with fewer checkpoints per file.
      # - Higher values = Fewer files with more checkpoints per file.
      #
      # Current setting (250 seconds):
      # - With 4-5 checkpoints/second, this should result in approximately 1000-1250 checkpoints per file.
      # - Provides good balance between file size and lookup efficiency.
      #
      # A batch will be finalized when ANY of these conditions are met:
      # 1. Time since first checkpoint in batch exceeds this value (250 seconds).
      # 2. An epoch transition occurs.
      # 3. Checkpoint sequence 1 is reached (special handling for genesis).
      #
      # Note: Actual checkpoint count per file may vary based on network activity and
      # checkpoint production rate.
      #
      commit-duration-seconds: 250
