[package]
name = "OFT"
version = "0.0.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
OApp = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", subdir = "packages/layerzero-v2/iota/contracts/oapps/oapp", rev = "main" }
OFTCommon = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", subdir = "packages/layerzero-v2/iota/contracts/oapps/oft/oft-common", rev = "main" }
PtbMoveCall = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", subdir = "packages/layerzero-v2/iota/contracts/ptb-builders/ptb-move-call", rev = "main" }


[addresses]
oft = "0x0"

[dev-dependencies]
SimpleMessageLib = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", subdir = "packages/layerzero-v2/iota/contracts/message-libs/simple-message-lib", rev = "main" }

[dev-addresses]
