services:
  fullnode:
    image: iotaledger/iota-node:_network_placeholder_
    ports:
      - "8084:8084/udp" # P2P port
      - "9000:9000/tcp" # JSON-RPC port
      - "9184:9184/tcp" # Metrics port
    volumes:
      - ./data:/opt/iota/:rw
    command: [
      "/usr/local/bin/iota-node",
      "--config-path",
      "/opt/iota/config/fullnode.yaml",
    ]
