name: Detect Changes
description: Defines variables indicating the parts of the code that changed
outputs:
  isDoc:
    description: True when changes happened to some documentation
    value: "${{ steps.diff.outputs.isDoc }}"
  isRust:
    description: True when changes happened to the Rust code
    value: "${{ steps.diff.outputs.isRust }}"
  isRustExample:
    description: True when changes happened to the Rust example code
    value: "${{ steps.diff.outputs.isRustExample }}"
  isRpc:
    description: True when changes happened to the RPC code
    value: "${{ steps.diff.outputs.isRpc }}"
  isPgIntegration:
    description: True when changes happened to the PG integration code
    value: "${{ steps.diff.outputs.isPgIntegration }}"
  isMoveExampleUsedByOthers:
    description: True when changes happened to the Move examples that are used by other tests
    value: "${{ steps.diff.outputs.isMoveExampleUsedByOthers }}"
  isRosetta:
    description: True when changes happened to the rosetta code
    value: "${{ steps.diff.outputs.isRosetta }}"
  isExternalCrates:
    description: True when changes happened in external crates
    value: "${{ steps.diff.outputs.isExternalCrates }}"
  isReleaseNotesEligible:
    description: True when changes happened in Release Notes eligible paths
    value: "${{ steps.diff.outputs.isReleaseNotesEligible }}"

runs:
  using: composite
  steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Detect Changes
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: diff
      with:
        filters: |
          isRust:
            - "consensus/**"
            - "crates/**"
            - "external-crates/**"
            - "iota-execution/**"
            - ".github/workflows/hierarchy.yml"
            - ".github/workflows/codecov.yml"
            - ".github/workflows/_rust.yml"
            - ".github/workflows/_rust_tests.yml"
            - ".github/workflows/_rust_lints.yml"
            - ".github/workflows/_external_rust_tests.yml"
            - ".github/workflows/_cargo_deny.yml"
            - "scripts/cargo_sort/cargo_sort.py"
            - "scripts/ci_tests/rust_tests.sh"
            - "Cargo.toml"
            - "Cargo.lock"
            - ".config/nextest.toml"
            - "rust-toolchain.toml"
          isRustExample:
            - "examples/custom-indexer/rust/**"
            - "examples/tic-tac-toe/cli/**"
            - "docs/examples/rust/**"
          isRpc:
            - "crates/iota-json-rpc/**"
            - "crates/iota-json-rpc-types/**"
            - "crates/iota-json-rpc-api/**"
            - "crates/iota-graphql-rpc/**"
            - ".github/workflows/hierarchy.yml"
            - ".github/workflows/_e2e.yml"
            - "Cargo.toml"
            - "Cargo.lock"
            - ".config/nextest.toml"
            - "rust-toolchain.toml"
          isPgIntegration:
            - "crates/iota-indexer/**"
            - "crates/iota-graphql-rpc/**"
            - "crates/iota-graphql-e2e-tests/**"
            - "crates/iota-framework/**"
            - "crates/iota-json-rpc-types/**"
            - "crates/iota-json-rpc-api/**"
            - ".github/workflows/hierarchy.yml"
            - ".github/workflows/_rust.yml"
            - ".github/workflows/_rust_tests.yml"
            - "Cargo.toml"
            - "Cargo.lock"
            - ".config/nextest.toml"
            - "rust-toolchain.toml"
          isDoc:
            - "docs/content/**"
            - "docs/site/**"
            - "*.mdx"
            - ".github/workflows/_docs_lint.yml"
            - ".github/workflows/_docusaurus.yml"
          isMoveExampleUsedByOthers:
            - "examples/move/basics/**"
            - "examples/move/coin/**"
            - "examples/move/nft/**"
            - "Cargo.toml"
            - ".github/workflows/_move_examples_rdeps_tests.yml"
          isRosetta:
            - ".github/scripts/rosetta/**"
            - "crates/iota-rosetta/**"
          isExternalCrates:
            - "external-crates/move/crates/**"
          isReleaseNotesEligible:
            - "consensus/**"
            - "crates/**"
            - "dashboards/**"
            - "doc/**"
            - "docker/**"
            - "dev-tools/**"
            - "setups/**"
            - "external-crates/**"
            - "kiosk/**"
            - "nre/**"
            - "iota-execution/**"
