name: Execution cut

on: workflow_call

concurrency:
  group: execution-cut-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  execution-cut:
    name: cutting a new execution layer
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Make cut
        run: ./scripts/execution_layer.py cut for_ci_test
      - name: Check execution builds
        run: cargo build -p iota-execution
