name: Rust tests

on:
  workflow_call:
    inputs:
      changedCrates:
        type: string
        required: false

concurrency:
  group: ext-rust-tests-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "error"
  # Don't emit giant backtraces in the CI logs.
  RUST_BACKTRACE: short
  CARGO_INCREMENTAL: 0
  # Allow more retries for network requests in cargo (downloading crates) and
  # rustup (installing toolchains). This should help to reduce flaky CI failures
  # from transient network timeouts or other issues.
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  # RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  TEST_ONLY_CHANGED_CRATES: true

jobs:
  test:
    name: Test external crates
    if: (!cancelled())
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: cargo nextest
        # test using filters, to only include changed crates and all their dependent crates
        run: |
          export CHANGED_CRATES="${{ inputs.changedCrates }}"
          ./scripts/ci_tests/rust_tests.sh external_crates

  check-unused-deps:
    name: Check Unused Dependencies (${{ matrix.flags }})
    if: (!cancelled())
    strategy:
      matrix:
        flags: ["--all-features", "--no-default-features"]
      fail-fast: false
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Run Cargo Udeps
        run: cargo +nightly ci-udeps-external ${{ matrix.flags }}
