name: Rust examples

on: workflow_call

concurrency:
  group: rust-examples-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "error"
  RUST_BACKTRACE: short
  CARGO_INCREMENTAL: 0

jobs:
  lint-examples:
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check examples
        # Set the globstar opt here to enable recursive glob.
        run: |
          shopt -s globstar
          for manifest in ./**/examples/**/Cargo.toml; do
              echo "Checking format for $manifest"
              cargo +nightly ci-fmt --manifest-path $manifest

              echo "Clippy linting for $manifest"
              cargo clippy --manifest-path $manifest --all-features

              echo "Checking unused dependencies of $manifest"
              cargo +nightly ci-udeps --manifest-path $manifest
          done
