name: Rust lints

on:
  workflow_call:
    inputs:
      isRust:
        type: boolean
      isRustExample:
        type: boolean

concurrency:
  group: rust-lints-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "error"
  # Don't emit giant backtraces in the CI logs.
  RUST_BACKTRACE: short
  # Disable incremental compilation.
  #
  # Incremental compilation is useful as part of an edit-build-test-edit cycle,
  # as it lets the compiler avoid recompiling code that hasn't changed. However,
  # on CI, we're not making small edits; we're almost always building the entire
  # project from scratch. Thus, incremental compilation on CI actually
  # introduces *additional* overhead to support making future builds
  # faster...but no future builds will ever occur in any given CI environment.
  #
  # See https://matklad.github.io/2021/09/04/fast-rust-builds.html#ci-workflow
  # for details.
  CARGO_INCREMENTAL: 0
  # Allow more retries for network requests in cargo (downloading crates) and
  # rustup (installing toolchains). This should help to reduce flaky CI failures
  # from transient network timeouts or other issues.
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustfmt:
    if: (!cancelled() && inputs.isRust)
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check Rust formatting
        run: cargo +nightly-2025-04-01 ci-fmt

  cargo-sort:
    if: (!cancelled() && inputs.isRust)
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check Cargo.toml format and sorting
        run: |
          pushd "scripts/cargo_sort"
          ./run.sh --skip-dprint
          popd
      - name: Check Cargo.toml diffs after formatting
        run: |
          if git status --porcelain | grep -q "Cargo.toml"; then
            echo "Cargo.toml files not formatted and/or sorted properly! Please run the 'scripts/cargo_sort/run.sh' script."
            git diff  # Show the actual diffs
            exit 1    # Fail the workflow
          fi

  examples:
    if: (!cancelled() && inputs.isRustExample)
    uses: ./.github/workflows/_rust_examples.yml

  clippy:
    if: (!cancelled() && !failure() && inputs.isRust)
    needs:
      - rustfmt
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      # TODO(bradh): debug and re-enable this; the caching is breaking the clippy build
      # Enable caching of the 'librocksdb-sys' crate by additionally caching the
      # 'librocksdb-sys' src directory which is managed by cargo
      # - uses: bmwill/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c # v1.4.0 # Fork of 'Swatinem/rust-cache' which allows caching additional paths
      #   with:
      #     path: ~/.cargo/registry/src/**/librocksdb-sys-*

      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: Check Clippy Lints
        run: cargo ci-clippy

      - name: Check Clippy Lints with msim
        run: |
          git clean -fd
          ./scripts/simtest/clippy.sh
