name: Hierarchy

on:
  push:
    branches:
      - "develop"
      - "devnet"
      - "testnet"
      - "mainnet"
      - "releases/iota-*-release"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  diff:
    runs-on: [ubuntu-latest]
    concurrency:
      group: diff-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    outputs:
      isRust: ${{ steps.diff.outputs.isRust }}
      isRustExample: ${{ steps.diff.outputs.isRustExample }}
      isRpc: ${{ steps.diff.outputs.isRpc }}
      isPgIntegration: ${{ steps.diff.outputs.isPgIntegration }}
      isMoveExampleUsedByOthers: ${{ steps.diff.outputs.isMoveExampleUsedByOthers }}
      isRosetta: ${{ steps.diff.outputs.isRosetta }}
      isDoc: ${{ steps.diff.outputs.isDoc }}
      isReleaseNotesEligible: ${{ steps.diff.outputs.isReleaseNotesEligible }}
      isExternalCrates: ${{ steps.diff.outputs.isExternalCrates }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Detect Changes (diff)
        uses: "./.github/actions/diffs"
        id: diff

  dprint-format:
    runs-on: [self-hosted-x64]
    concurrency:
      group: dprint-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check dprint formatting
        run: dprint check

  typos:
    uses: ./.github/workflows/_typos.yml

  license-check:
    name: license-check
    concurrency:
      group: license-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    needs: diff
    if: (!cancelled() && needs.diff.outputs.isRust == 'true')
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Run license check
        run: cargo ci-license

  docusaurus:
    needs: diff
    if: (!cancelled() && needs.diff.outputs.isDoc == 'true' && !github.event.pull_request.draft)
    uses: ./.github/workflows/_docusaurus.yml

  docs-lint:
    needs: diff
    if: (!cancelled() && needs.diff.outputs.isDoc == 'true')
    uses: ./.github/workflows/_docs_lint.yml

  rust:
    needs:
      - diff
      - dprint-format
      - license-check
      - typos
    if: (!cancelled() && !failure())
    uses: ./.github/workflows/_rust.yml
    secrets: inherit
    with:
      isRust: ${{ needs.diff.outputs.isRust == 'true' }}
      isRustExample: ${{ needs.diff.outputs.isRustExample == 'true' }}
      isPgIntegration: ${{ needs.diff.outputs.isPgIntegration == 'true' }}
      isMoveExampleUsedByOthers: ${{ needs.diff.outputs.isMoveExampleUsedByOthers == 'true' }}

  rosetta:
    needs:
      - diff
      - dprint-format
      - typos
    if: |
      !cancelled() && !failure() &&
      (needs.diff.outputs.isRosetta == 'true' || needs.diff.outputs.isRust == 'true')
    uses: ./.github/workflows/_rosetta.yml

  move-ide:
    needs:
      - diff
      - dprint-format
      - license-check
      - typos
    if: (!cancelled() && !failure()) && needs.diff.outputs.isExternalCrates == 'true' && github.event.pull_request.draft == false
    uses: ./.github/workflows/_move_ide.yml

  split-cluster:
    needs:
      - diff
      - rust
    if: (!cancelled() && !failure()) && needs.diff.outputs.isRust == 'true' && github.event.pull_request.draft == false
    uses: ./.github/workflows/_split_cluster.yml
